"""
Dione AI — Heartbeat / Proactive Agent

The "pulse" of Dione. Runs in the background and:
- Monitors learned user habits/patterns
- Generates proactive suggestions at the right moment
- Prepares drafts, reminders, daily summaries
- Makes the AI feel alive — it doesn't just respond, it initiates

The BeatEvent is pushed to connected WebSocket clients so the
Flutter app can display proactive cards, notifications, and
UI changes.
"""

import asyncio
import json
import time
from pathlib import Path
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
from typing import Optional, Callable, Awaitable
from loguru import logger


@dataclass
class BeatEvent:
    """
    A proactive event generated by Dione's heartbeat.
    
    These are pushed to the UI without user prompt.
    """
    event_type: str          # "suggestion", "reminder", "insight", "greeting", "mood_shift"
    title: str               # Short headline
    body: str                # Detail text
    priority: str = "normal" # "low", "normal", "high", "urgent"
    action: Optional[dict] = None  # Optional action the user can take
    # e.g., {"type": "send_email", "draft": "...", "to": "..."}
    ui_component: Optional[dict] = None  # UI rendering hint
    timestamp: float = field(default_factory=time.time)
    expires_at: Optional[float] = None   # Auto-dismiss after this time

    def to_dict(self) -> dict:
        d = asdict(self)
        d["timestamp"] = self.timestamp
        return d


@dataclass
class HabitPattern:
    """A recognized recurring pattern in user behavior."""
    pattern_id: str
    description: str          # "Emails team report every Monday 9am"
    action_type: str          # "email", "file", "command", "reminder"
    trigger_schedule: str     # cron-like: "Mon 09:00", "daily 17:00"
    target: str = ""          # email address, file path, etc.
    template: str = ""        # draft content template
    confidence: float = 0.5   # 0-1, strengthens with repetition
    last_triggered: float = 0.0
    trigger_count: int = 0
    active: bool = True


class HeartbeatScheduler:
    """
    Dione's background heartbeat.
    
    Periodically checks for:
    1. Habit patterns that should be triggered now
    2. Time-based insights (morning summary, evening recap)
    3. System events worth notifying about
    4. Mood-driven spontaneous interactions
    """

    # Adaptive intervals (seconds) based on user activity
    INTERVAL_ACTIVE = 30       # User active in last 5 min
    INTERVAL_IDLE = 120        # 5-30 min since last interaction
    INTERVAL_INACTIVE = 300    # 30-120 min since last interaction
    INTERVAL_SLEEPING = 900    # 120+ min or outside active hours

    def __init__(self, data_dir: str = "data"):
        self._data_dir = Path(data_dir)
        self._data_dir.mkdir(parents=True, exist_ok=True)
        self._habits_path = self._data_dir / "habits.json"

        self.patterns: list[HabitPattern] = []
        self._event_queue: asyncio.Queue[BeatEvent] = asyncio.Queue()
        self._subscribers: list[Callable[[BeatEvent], Awaitable[None]]] = []
        self._running = False
        self._task: Optional[asyncio.Task] = None
        
        # Activity tracking for adaptive intervals
        self._last_user_activity: float = time.time()
        self._current_state: str = "active"  # active, idle, inactive, sleeping
        
        # Services injected later
        self._profile_manager = None
        self._personality_engine = None

        self._load_patterns()

    def set_profile_manager(self, pm):
        self._profile_manager = pm

    def set_personality_engine(self, pe):
        self._personality_engine = pe

    def _load_patterns(self):
        """Load habit patterns from disk."""
        if self._habits_path.exists():
            try:
                data = json.loads(self._habits_path.read_text(encoding="utf-8"))
                self.patterns = [HabitPattern(**p) for p in data]
                logger.info(f"Loaded {len(self.patterns)} habit patterns")
            except Exception as e:
                logger.warning(f"Could not load habits: {e}")

    def save_patterns(self):
        """Persist habit patterns."""
        try:
            data = [asdict(p) for p in self.patterns]
            self._habits_path.write_text(
                json.dumps(data, indent=2), encoding="utf-8"
            )
        except Exception as e:
            logger.error(f"Failed to save habits: {e}")

    # ------------------------------------------------------------------
    # Pattern management
    # ------------------------------------------------------------------

    def learn_pattern(self, description: str, action_type: str,
                      trigger_schedule: str, target: str = "",
                      template: str = "", confidence: float = 0.5) -> HabitPattern:
        """Register a new habit pattern."""
        pattern = HabitPattern(
            pattern_id=f"habit_{len(self.patterns)}_{int(time.time())}",
            description=description,
            action_type=action_type,
            trigger_schedule=trigger_schedule,
            target=target,
            template=template,
            confidence=confidence,
        )
        self.patterns.append(pattern)
        self.save_patterns()
        logger.info(f"🎯 Learned new habit: {description}")
        return pattern

    def strengthen_pattern(self, pattern_id: str):
        """Increase confidence in a pattern (user confirmed it)."""
        for p in self.patterns:
            if p.pattern_id == pattern_id:
                p.confidence = min(1.0, p.confidence + 0.15)
                p.trigger_count += 1
                logger.debug(f"Strengthened habit: {p.description} → {p.confidence:.2f}")
                self.save_patterns()
                return

    # ------------------------------------------------------------------
    # Heartbeat loop
    # ------------------------------------------------------------------

    async def start(self):
        """Start the heartbeat background loop."""
        if self._running:
            return
        self._running = True
        self._task = asyncio.create_task(self._heartbeat_loop())
        logger.info("💓 Heartbeat started")

    async def stop(self):
        """Stop the heartbeat."""
        self._running = False
        if self._task:
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
        logger.info("💓 Heartbeat stopped")

    async def _heartbeat_loop(self):
        """Main background loop — Dione's pulse with adaptive intervals."""
        while self._running:
            try:
                await self._tick()
            except Exception as e:
                logger.error(f"Heartbeat tick error: {e}")
            
            interval = self._compute_interval()
            await asyncio.sleep(interval)

    def record_user_activity(self):
        """Called when the user sends a message or interacts with Dione."""
        self._last_user_activity = time.time()
        self._current_state = "active"

    def _compute_interval(self) -> float:
        """
        Determine heartbeat interval based on user activity.
        Combines real interaction data with profile active hours.
        """
        now = time.time()
        elapsed = now - self._last_user_activity
        hour = int(datetime.now().strftime("%H"))

        # Check if outside active hours from profile
        active_hours = []
        if self._profile_manager and hasattr(self._profile_manager, 'profile'):
            usage = getattr(self._profile_manager.profile, 'usage', None)
            if usage:
                active_hours = getattr(usage, 'active_hours', [])

        outside_active = False
        if active_hours and len(active_hours) >= 2:
            # If hour is NOT within ±2 hours of any known active hour
            outside_active = all(
                abs(hour - ah) > 2 and abs(hour - ah - 24) > 2 and abs(hour - ah + 24) > 2
                for ah in active_hours
            )

        # Determine state
        if elapsed > 7200 or (elapsed > 3600 and outside_active):  # 2h+ or 1h+ AND outside active hours
            self._current_state = "sleeping"
            return self.INTERVAL_SLEEPING
        elif elapsed > 1800:  # 30+ min
            self._current_state = "inactive"
            return self.INTERVAL_INACTIVE
        elif elapsed > 300:  # 5+ min
            self._current_state = "idle"
            return self.INTERVAL_IDLE
        else:
            self._current_state = "active"
            return self.INTERVAL_ACTIVE

    @property
    def activity_state(self) -> str:
        """Current user activity state."""
        return self._current_state

    @property
    def current_interval(self) -> float:
        """Current heartbeat interval in seconds."""
        return self._compute_interval()

    async def _tick(self):
        """Single heartbeat tick — check patterns and generate events."""
        now = datetime.now()

        # 1. Check habit patterns
        for pattern in self.patterns:
            if not pattern.active or pattern.confidence < 0.4:
                continue
            if self._should_trigger(pattern, now):
                event = self._create_habit_event(pattern)
                if event:
                    await self._emit(event)
                    pattern.last_triggered = time.time()

        # 2. Time-based events
        await self._check_time_events(now)

        # 3. Mood-based spontaneous interaction
        if self._personality_engine:
            self._personality_engine.react_to_time_of_day()

    def _should_trigger(self, pattern: HabitPattern, now: datetime) -> bool:
        """Check if a habit pattern should trigger now."""
        schedule = pattern.trigger_schedule.lower().strip()
        
        # Don't re-trigger within 30 minutes
        if pattern.last_triggered and (time.time() - pattern.last_triggered) < 1800:
            return False

        # Parse simple schedules
        # "daily HH:MM"
        if schedule.startswith("daily"):
            try:
                time_part = schedule.split(" ", 1)[1]
                hour, minute = map(int, time_part.split(":"))
                return now.hour == hour and now.minute == minute
            except (ValueError, IndexError):
                return False

        # "Mon HH:MM", "Tue HH:MM", etc.
        day_map = {"mon": 0, "tue": 1, "wed": 2, "thu": 3, "fri": 4, "sat": 5, "sun": 6}
        for day_name, day_num in day_map.items():
            if schedule.startswith(day_name):
                if now.weekday() != day_num:
                    return False
                try:
                    time_part = schedule.split(" ", 1)[1]
                    hour, minute = map(int, time_part.split(":"))
                    return now.hour == hour and now.minute == minute
                except (ValueError, IndexError):
                    return False

        # "every N hours"
        if "every" in schedule and "hour" in schedule:
            try:
                n = int(schedule.split("every")[1].split("hour")[0].strip())
                elapsed = time.time() - (pattern.last_triggered or 0)
                return elapsed >= n * 3600
            except ValueError:
                return False

        return False

    def _create_habit_event(self, pattern: HabitPattern) -> Optional[BeatEvent]:
        """Create a proactive event from a habit pattern."""
        return BeatEvent(
            event_type="suggestion",
            title=f"🔔 {pattern.description}",
            body=(
                f"Based on your routine, it's time to: {pattern.description}. "
                f"I've been tracking this pattern (confidence: {pattern.confidence:.0%})."
            ),
            priority="normal" if pattern.confidence < 0.8 else "high",
            action={
                "type": pattern.action_type,
                "target": pattern.target,
                "template": pattern.template,
                "pattern_id": pattern.pattern_id,
            },
            ui_component={
                "type": "action_card",
                "variant": "proactive",
                "actions": ["confirm", "dismiss", "snooze"],
            },
        )

    async def _check_time_events(self, now: datetime):
        """Generate time-based events."""
        # Morning greeting (8 AM)
        if now.hour == 8 and now.minute == 0:
            profile_ctx = ""
            if self._profile_manager:
                p = self._profile_manager.profile
                if p.name != "User":
                    profile_ctx = f"Good morning, {p.name}! "
            
            await self._emit(BeatEvent(
                event_type="greeting",
                title="☀️ Good Morning!",
                body=f"{profile_ctx}Here's what I know about today.",
                priority="low",
                ui_component={
                    "type": "morning_summary",
                    "variant": "full_width",
                    "sections": ["weather", "habits", "reminders"],
                },
            ))

        # Evening wrap-up (9 PM)
        if now.hour == 21 and now.minute == 0:
            await self._emit(BeatEvent(
                event_type="insight",
                title="🌙 Daily Recap",
                body="Here's a summary of what we accomplished today.",
                priority="low",
                ui_component={
                    "type": "daily_recap",
                    "variant": "card",
                    "sections": ["tasks_completed", "tools_used", "mood_journey"],
                },
            ))

    # ------------------------------------------------------------------
    # Event emission
    # ------------------------------------------------------------------

    async def _emit(self, event: BeatEvent):
        """Push event to subscribers and queue."""
        self._event_queue.put_nowait(event)
        logger.info(f"💓 Beat event: {event.event_type} — {event.title}")

        for subscriber in self._subscribers:
            try:
                await subscriber(event)
            except Exception as e:
                logger.error(f"Subscriber error: {e}")

    def subscribe(self, callback: Callable[[BeatEvent], Awaitable[None]]):
        """Subscribe to heartbeat events (for WebSocket push)."""
        self._subscribers.append(callback)

    def unsubscribe(self, callback: Callable[[BeatEvent], Awaitable[None]]):
        """Remove a subscriber."""
        self._subscribers = [s for s in self._subscribers if s is not callback]

    async def get_pending_events(self) -> list[BeatEvent]:
        """Drain the event queue (for REST polling)."""
        events = []
        while not self._event_queue.empty():
            try:
                events.append(self._event_queue.get_nowait())
            except asyncio.QueueEmpty:
                break
        return events

    # ------------------------------------------------------------------
    # Insight generation
    # ------------------------------------------------------------------

    def get_proactive_context(self) -> str:
        """
        Generate proactive context to include in LLM prompts.
        
        This makes the AI aware of upcoming habits and patterns.
        """
        upcoming = []
        now = datetime.now()

        for pattern in self.patterns:
            if pattern.active and pattern.confidence > 0.5:
                upcoming.append(
                    f"- {pattern.description} "
                    f"(schedule: {pattern.trigger_schedule}, "
                    f"confidence: {pattern.confidence:.0%})"
                )

        if not upcoming:
            return ""

        return (
            "Known user habits/patterns:\n" +
            "\n".join(upcoming[:5]) +
            "\nIf relevant, proactively mention these."
        )
